function(livox_mid360_apply_sanitizers target)
  set(flags "")
  if(LIVOX_MID360_ENABLE_ASAN)
    list(APPEND flags -fsanitize=address -fno-omit-frame-pointer)
  endif()
  if(LIVOX_MID360_ENABLE_UBSAN)
    list(APPEND flags -fsanitize=undefined -fno-sanitize-recover=all)
  endif()
  if(flags)
    target_compile_options(${target} PUBLIC ${flags})
    target_link_options(${target} PUBLIC ${flags})
  endif()
endfunction()
